name: flow_dart_sdk
description: Flow Dart SDK
version: 0.0.2

environment:
  sdk: ">=2.18.6"
  flutter: "3.3.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: any
  logging: any
  rlp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
